version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing dependencies...

  build:
    commands:
      - echo Building the Lambda function...
      - zip -r function.zip .  # 打包 Lambda 函数代码

  post_build:
    commands:
      - echo Uploading the Lambda function to S3...
      - aws s3 cp function.zip s3://test-bucket-dr/deployment/kkk.zip
      - echo Publishing new Lambda version...
      - NEW_VERSION=$(aws lambda publish-version --function-name kkk --query 'Version' --output text)
      - echo Creating a new deployment in CodeDeploy...

      # 获取 S3 文件的 ETag
      - NEW_ETAG=$(aws s3api head-object --bucket test-bucket-dr --key deployment/kkk.zip --query 'ETag' --output text)

      # 创建 CodeDeploy 部署（确保这个命令是一个字符串）
      - aws deploy create-deployment --application-name daisyTestDeploy --deployment-group-name daisyDeloymentGroup --s3-location "bucket=test-bucket-dr,key=deployment/kkk.zip,bundleType=zip,eTag=$NEW_ETAG"

artifacts:
  files:
    - '**/*'
