version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the Lambda function...
      - zip -r function.zip .  # 打包 Lambda 函数代码

  post_build:
    commands:
      - echo Uploading the Lambda function to S3...
      - aws s3 cp function.zip s3://test-bucket-dr/deployment/kkk.zip
      - echo Publishing new Lambda version...
      - NEW_VERSION=$(aws lambda publish-version --function-name kkk --query 'Version' --output text)
      - echo New Lambda version: $NEW_VERSION
      - echo Creating a new deployment in CodeDeploy...
      - aws deploy create-deployment \
          --application-name daisyTestDeploy \
          --deployment-group-name daisyDeloymentGroup \
          --s3-location bucket=test-bucket-dr/deployment/,key=kkk.zip,bundleType=zip,eTag=your-etag
artifacts:
  files:
    - '**/*'
