version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing dependencies...

  build:
    commands:
      - echo Building the Lambda function...
      - zip -r function.zip .  # 打包 Lambda 函数代码

  post_build:
    commands:
      - echo Uploading the Lambda function to S3...
      - aws s3 cp function.zip s3://test-bucket-dr/deployment/kkk.zip

      # 更新 Lambda 函数的代码，指向 S3 中的 ZIP 文件
      - echo Updating Lambda function code...
      - aws lambda update-function-code --function-name kkk --s3-bucket test-bucket-dr --s3-key deployment/kkk.zip

      # 发布新的 Lambda 版本，添加重试机制
      - echo Publishing new Lambda version...
      - |
        for i in {1..5}; do
          NEW_VERSION=$(aws lambda publish-version --function-name kkk --query 'Version' --output text) && break || {
            echo "Publish version failed, retrying in 10 seconds... (Attempt $i/5)"
            sleep 10
          }
        done

      # 获取 S3 文件的 ETag
      - echo Getting the ETag for the uploaded S3 object...
      - NEW_ETAG=$(aws s3api head-object --bucket test-bucket-dr --key deployment/kkk.zip --query 'ETag' --output text)

      # 创建 Lambda 别名 blue，指向新版本
      - echo Creating a new alias 'blue' for the Lambda function...
      - aws lambda create-alias --function-name kkk --name blue --function-version $NEW_VERSION

      # 创建 CodeDeploy 部署
      - echo Creating a new deployment in CodeDeploy...
      - aws deploy create-deployment \
        --application-name daisyTestDeploy \
        --deployment-group-name daisyDeloymentGroup \
        --s3-location "bucket=test-bucket-dr,key=deployment/kkk.zip,bundleType=zip,eTag=$NEW_ETAG" \
        --description "Deployment for Lambda version $NEW_VERSION"

artifacts:
  files:
    - '**/*'